# Generated by Django 4.2.11 on 2024-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test2',
            },
        ),
        migrations.RenameModel(
            old_name='SimpleTable',
            new_name='SimpleTable1',
        ),
        migrations.AlterModelTable(
            name='simpletable1',
            table='test1',
        ),
    ]
